$schema: https://veupathdb.github.io/vdi-service/schema/config/full-config.json

definitions:
  genomicsProjects: &genomicsProjects
  - AmoebaDB
  - CryptoDB
  - ClinEpiDB
  - FungiDB
  - GiardiaDB
  - HostDB
  - MicrosporidiaDB
  - PiroplasmaDB
  - PlasmoDB
  - ToxoDB
  - TrichDB
  - TriTrypDB
  - VectorBase
  - UniDB
  vdiAppDbLDAP: &vdiAppDbLDAP ${env:APP_DB_LDAP}
  vdiAppDbUsername: &vdiAppDbUsername ${env:APP_DB_USERNAME}
  vdiAppDbPassword: &vdiAppDbPassword ${env:APP_DB_PASSWORD}
  vdiSchemaPass: &vdiSchemaPass ${env:VDI_APPDB_SCHEMA_PASS}
  vdiControlSchema: &vdiControlSchema vdi_control_prod_${env:LOCATION_INDICATOR}
  vdiDataSchema: &vdiDataSchema vdi_datasets_prod_${env:LOCATION_INDICATOR}
  controlDbConfig: &controlDbConfig
    schema: *vdiControlSchema
    username: *vdiAppDbUsername
    password: *vdiAppDbPassword
    lookupCn: *vdiAppDbLDAP
  dataDbConfig: &dataDbConfig
    schema: *vdiDataSchema
    username: *vdiAppDbUsername
    password: *vdiAppDbPassword
    lookupCn: *vdiAppDbLDAP

containerCore:
  authentication:
    oauth:
      clientId: ${env:OAUTH_CLIENT_ID}
      clientSecret: ${env:OAUTH_CLIENT_SECRET}
      url: https://eupathdb.org/oauth
    adminToken: ${env:ADMIN_AUTH_TOKEN}

vdi:
  siteBuild: ${env:SITE_BUILD}

  sharedTargetDbPooling:
    poolSize: ${env:APP_DB_POOL_SIZE}

  ldap:
    servers: ${env:LDAP_SERVER}
    baseDn: ${env:DB_LOOKUP_BASE_DN}

  objectStore:
    bucketName: ${env:S3_BUCKET}
    server:
      host: ${env:S3_HOST}
      port: ${env:S3_PORT}
    accessToken: ${env:S3_ACCESS_TOKEN}
    secretKey: ${env:S3_SECRET_KEY}

  rabbit:
    global:
      connection:
        server:
          host: ${env:GLOBAL_RABBIT_HOST}
          port: ${env:GLOBAL_RABBIT_PORT}
        tls: ${env:GLOBAL_RABBIT_USETLS}
        username: ${env:GLOBAL_RABBIT_USERNAME}
        password: ${env:GLOBAL_RABBIT_PASSWORD}
      exchange:
        name:  ${env:GLOBAL_RABBIT_VDI_EXCHANGE_NAME}
      queue:
        name: ${env:GLOBAL_RABBIT_VDI_QUEUE_NAME}
      routing:
        key:  ${env:GLOBAL_RABBIT_VDI_ROUTING_KEY}

  kafka:
    servers:
    - kafka:9092

  cacheDb:
    username: vdi
    password: ${env:CACHE_DB_PASSWORD}
    server: cache-db:5432

  plugins:
    bigwig:
      server: bigwig:80
      dataTypes:
      - name: bigwigfiles
        category: bigWig
        version: 1.0
        # 500MiB
        maxFileSize: 524288000
        allowedFileExtensions: [ ".bw", ".bigwig" ]
        usesDataProperties: true
        projectIds: *genomicsProjects
    biom:
      server: biom:80
      dataTypes:
      - name: biom
        category: BIOM
        version: 1.0
        # 100MiB
        maxFileSize: 104857600
        allowedFileExtensions: [ ".biom" ]
        projectIds:
        - MicrobiomeDB
    genelist:
      server: genelist:80
      dataTypes:
      - name: genelist
        category: Gene List
        version: 1.0
        projectIds: *genomicsProjects
    noop:
      server: noop:80
      dataTypes:
      - name: lightweight
        category: Lightweight
        version: 1.0
        typeChangesEnabled: true
    rnaseq:
      server: rnaseq:80
      dataTypes:
      - name: rnaseq
        category: RNA-Seq
        version: 1.0
        # 10GiB
        maxFileSize: 10737418240
        projectIds: *genomicsProjects
    wrangler:
      server: wrangler:80
      dataTypes:
      - name: phenotype
        category: Phenotype
        version: 1.0
        # 10GiB
        maxFileSize: 10737418240
        allowedFileExtensions: [ ".txt", ".tsv" ]
        projectIds: *genomicsProjects
      - name: isasimple
        category: ISA Study
        version: 1.0
        projectIds:
        - ClinEpiDB

  installTargets:
  - targetId: AmoebaDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig

  - targetId: ClinEpiDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig
    metaValidation:
      allOf:
      - properties:
          studyCharacteristics:
            required:
            - studyDesign
            - studyType
        required:
        - studyCharacteristics
      # fundamental fields
      - if:
          properties:
            visibility:
              not: { const: "private" }
          required: [ "visibility" ]
        then:
          properties:
            studyCharacteristics:
              properties:
                countries: { minItems: 1 }
                studySpecies: { minItems: 1 }
                outcomes: { minItems: 1 }
                associatedFactors: { minItems: 1 }
                sampleTypes: { minItems: 1 }
              required:
              - countries
              - years
              - studySpecies
              - outcomes
              - associatedFactors
              - participantAges
              - sampleTypes
      # ensure we have a program name when project name is "other"
      - if:
          properties:
            projectName:
              const: "other"
          required: [ "projectName" ]
        then:
          required: [ programName ]

  - targetId: CryptoDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig

  - targetId: FungiDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig

  - targetId: GiardiaDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig

  - targetId: HostDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig

  - targetId: MicrosporidiaDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig

  - targetId: PiroplasmaDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig

  - targetId: PlasmoDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig

  - targetId: ToxoDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig

  - targetId: TrichDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig

  - targetId: TriTrypDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig

  - targetId: VectorBase
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig

  - targetId: UniDB
    targetName: VEuPathDB
    controlDb: *controlDbConfig
    dataDb: *dataDbConfig
